### ISSUE TITLE
Wiki Review

### ISSUE THREAD

**Issue by jmeyer90** [brandonheld/Etsy-Bakery#1]
1. MVP List
* All descriptions should be full sentences with proper grammar. If a recruiter or potential employer is reading this page, they should be able to understand exactly what the functionality is without guessing. All descriptions should be based off of the functionality it provides to the user, not the contents of each feature.
* Include expected completion dates

2. Schema
* Include any associations for your tables.

3. Complete back-end routes, front-end routes, and sample state,

**Comment by brandonheld** [comment]
Changed the Wiki based on the feed back given.
